SampleTask.Web/Controllers/PlaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SampleTask.Web.Models;

namespace SampleTask.Web.Controllers
{
    public class PlaceController : Controller
    {
        // GET: Place
        private static Places _places = new Places();
        public ActionResult Index()
        {
            return View(_places.PlaceList);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(PlaceModels placeModel)
        {
            _places.CreatePlace(placeModel);
            return RedirectToAction("Index");
        }

        public ActionResult Edit(string name)
        {
            if (name == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PlaceModels place = _places.GetPlace(name);
            if (place == null)
            {
                return HttpNotFound();
            }
            return View(place);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PlaceModels place)
        {
            _places.UpdatePlace(place);
            return RedirectToAction("Index");
        }

        public ActionResult Details(string name)
        {
            if (name == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PlaceModels place = _places.GetPlace(name);
            if (place == null)
            {
                return HttpNotFound();
            }
            return View(place);
        }

        public ActionResult Delete(string name)
        {
            if (name == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PlaceModels place = _places.GetPlace(name);
            if (place == null)
            {
                return HttpNotFound();
            }
            _places.RemovePlace(place);
            return RedirectToAction("Index");
        }

    }
}

SampleTask.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Sample Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Sample Application", "Index", "Place", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Sample Application - Carlo</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>